### ISSUE TITLE
有没有方便的方法可以隐藏所有红点？

### ISSUE THREAD

**Issue by ctwlilei** [GJGroup/GJRedDot#2]
退出登录时候用到。
现在的方法是设置了[self setRedDotKey:@"测试" refreshBlock:^(BOOL show) {
        item2.showRedDot = show;
    } handler:self];
[self resetRedDotState:NO forKey:YKMyIconDot];
需要设置代理并且拿到控件才能够隐藏。
能否实现一个清空的方法？

**Comment by wangyutao0424** [comment]
您的需求跟我们项目的有点不一样，我们是上一些新的功能会有红点展示，所以只需要增加个key就可以了，初始化默认显示；
我看到了您的PR和需求，跟我们的需求正好相反，如果要解决这个问题，需要处理的更加灵活，直接设成显示or隐藏都会有所不妥，请稍等一段时间，等我考虑一下，选择一个好的方法解决这个问题。
感谢你的建议

**Comment by ctwlilei** [comment]
感谢！不过您没有回答我上面的问题。
我想在任何地方调用[self resetRedDotState:NO forKey:YKMyIconDot]; 都起作用。不仅仅是设置代理的地方

**Comment by wangyutao0424** [comment]
我不是很明白您上面的问题；
[self setRedDotKey:@"测试" refreshBlock:^(BOOL show) {
      item2.showRedDot = show;
} handler:self];
这个方法是需要写在您block中控件声明周期相关的地方，这个handler就是控制item2声明周期的对象，打个比方：在一个Cell上面有一个icon，那么这个icon的handler可以是icon自己，也可以是这个cell，因为当这个cell或icon被release的时候，我可以将这个刷新的block也一起释放掉，主要是这个目的。
您说的[self resetRedDotState:NO forKey:YKMyIconDot]，这个方法是在所以地方都生效的，他reset的是这个key所对应的本地缓存，上面那个方法当第一次调用的时候是取缓存并调用block进行icon刷新，以及后面等待有任何地方reset相同key或者关联的key的时候也进行刷新；
您可以测试一下：在这个项目的Demo中，将FirstItemViewController类中的- (IBAction)showButton:(UIButton *)sender 方法里加一行代码    [self resetRedDotState:NO forKey:GJSunnyxxKey];然后您可以点击这个页面中的show按钮执行这行代码，然后跳到第二个tab，进到里面看这个SunnyxxButton的小红点，应该是消失了的。

**Comment by wangyutao0424** [comment]
我不是很明白您上面的问题；
[self setRedDotKey:@"测试" refreshBlock:^(BOOL show) {
      item2.showRedDot = show;
} handler:self];
这个方法是需要写在您block中控件声明周期相关的地方，这个handler就是控制item2声明周期的对象，打个比方：在一个Cell上面有一个icon，那么这个icon的handler可以是icon自己，也可以是这个cell，因为当这个cell或icon被release的时候，我可以将这个刷新的block也一起释放掉，主要是这个目的。
您说的[self resetRedDotState:NO forKey:YKMyIconDot]，这个方法是在所以地方都生效的，他reset的是这个key所对应的本地缓存，上面那个方法当第一次调用的时候是取缓存并调用block进行icon刷新，以及后面等待有任何地方reset相同key或者关联的key的时候也进行刷新；
您可以测试一下：在这个项目的Demo中，将FirstItemViewController类中的- (IBAction)showButton:(UIButton *)sender 方法里加一行代码    [self resetRedDotState:NO forKey:GJSunnyxxKey];然后您可以点击这个页面中的show按钮执行这行代码，然后跳到第二个tab，进到里面看这个SunnyxxButton的小红点，应该是消失了的。

**Comment by ctwlilei** [comment]
抱歉我没能都说的清楚。我将按照步骤为您展示这个bug
1. 在这个项目的Demo中，将FirstItemViewController类中的- (IBAction)showButton:(UIButton *)sender 方法里加一行代码 [self resetRedDotState:YES forKey:GJSunnyxxKey];  注意这里是写YES不是NO
2.进入SecondDetailViewController 里面，点掉三个红点，让他们都隐藏。
3.跳回第一个tab 点击showButton  方法的按钮
红点只有SunnyxxButton 显示了。它的两个父节点并没有相应的刷新。应该的效果是它们都需要同时都展示红点。【 如果杀掉应用，重新进入可以看到红点都刷新好了】

**Comment by wangyutao0424** [comment]
![123](https://cloud.githubusercontent.com/assets/4385589/17437418/24ee4de8-5b50-11e6-8d0a-d5ce51c365fe.gif)
我试了下，并无问题啊…好奇怪…

**Comment by ctwlilei** [comment]
对了。是我改过代码后引起的。我改了默认启动不展示后引起的。抱歉。

**Comment by ctwlilei** [comment]
同样的步骤我这块就是不能够让父节点实时同时显示。我也是在ios9.3的模拟器上
![untitled](https://cloud.githubusercontent.com/assets/13645606/17460780/56912abc-5ca6-11e6-9d59-bcea2f89ea0c.gif)

**Comment by ctwlilei** [comment]
您好！现已查明原因。
<img width="445" alt="2016-08-07 2 17 21" src="https://cloud.githubusercontent.com/assets/13645606/17460841/c2d36bf6-5ca9-11e6-9375-0a618c03da43.png">
通过github客户端打开和下载zip打开的两份代码是不一致的。
下载zip打开运行正常。
通过github客户端打开会出现我上面描述的情况。
再次感谢！！非常棒的库。

**Comment by wangyutao0424** [comment]
您好，您提到的功能，后面我会加上：）

**Comment by ctwlilei** [comment]
现在连Download ZIP下来的也不行了。会出现我上面gif展示的问题

**Comment by wangyutao0424** [comment]
你下的应该是你改过的代码，你看下是你fork的吧，不是我原工程的

**Comment by ctwlilei** [comment]
![image](https://cloud.githubusercontent.com/assets/13645606/17471027/a7d8bfb6-5d73-11e6-8a4f-3704234bf3f4.png)
已经试过好几次。确定没有下错代码。我也到代码里排查了。确认是没有我改过的代码。

**Comment by ctwlilei** [comment]
我现在是点击【show/to show】button  有很小概率可以让第二个tabbar还有那个捡肥图标展示红点。就是正常运行。大部分时候还是不能够正确展示红点。就像上面gif图那样。或者是我下载的代码确实有问题。能否告诉我正确的下载方式。

**Comment by wangyutao0424** [comment]
我仔细查看了下，确实会出现您说的问题，我已经修正。非常感谢您！
您的需求我后面也会加入，感谢支持！

**Comment by ctwlilei** [comment]
棒！可以了😄👍

**Comment by wangyutao0424** [comment]
已经加入您的需求

**Comment by ctwlilei** [comment]
感谢！！👍🏻👍🏻👍🏻
