### ISSUE TITLE
红点内是文字的情况下，偏移失效

### ISSUE THREAD

**Issue by luowen1991** [GJGroup/GJRedDot#5]
如题，当红点内有内容时，view.redDotOffest失效，大神能修复下嘛

**Comment by wangyutao0424** [comment]
您好，因为UITabBarItem的显示文字的时候是用的系统的badge，无法设置offset，所以我想与其统一就没有左view的badge offset；
不过您提出这个需求，我暂时将offset设置成可以影响badge的offset，不知道这样做是否好，是否会影响其他用户的需求，或者说我单独增加一个badgeOffset更好？
请给出一些建议；
我暂时将改动提交到github，并暂时不加入到pod中，等此项修改完善后再更新pod
非常感谢您的建议

**Comment by luowen1991** [comment]
普通view设置文字内容时，badgeOffset也失效，我看了下是您把label的约束固定了，导致传入文字时,调整badgeOffset也失效

**Comment by luowen1991** [comment]
其实这并不会影响其他用户的需求吧，如果他不想偏移的话不设置即可，谢谢大神的回复.

**Comment by wangyutao0424** [comment]
我还是觉得多加一个badgeOffset比较好，因为有些人可能只想对小红点进行offset或者只想对badge进行offset，或者2个的offset不相同（根据当前项目UI设计），如果用一个offset来控制显然不是很好的方式，我又更改了一下，增加了badgeOffset的设置

**Comment by wangyutao0424** [comment]
你可以在Demo中的第二个item来看下效果

**Comment by luowen1991** [comment]
楼主考虑的很全面，我发现还有个小问题，就是当我badgeValue有值得时候，不是小红点时，无法隐藏了,不知我是不是没看到那个方法

**Comment by wangyutao0424** [comment]
是的，其实这个也是希望跟系统的UITabBarItem保持一致，系统的badge是否隐藏取决于badge是否为空，毕竟小红点是小红点，显示文字的badge是badge，都用一个方法控制不是非常的好，所以这个很难统一，怎么设计都会有使用者因为思维方式不一样觉得不对劲，所以就先这样啦，总之你可以通过badgeValue == nil来控制隐藏，试试吧

**Comment by luowen1991** [comment]
恩恩 好的
